const { Sequelize } = require('sequelize');
const path = require('path');
const fs = require('fs');

// Determine environment (default to development)
const env = process.env.NODE_ENV || 'development';

// Load database configuration
// The config.json expects paths relative to where sequelize-cli runs from (project root)
// but here we are in src/db. We need to adjust or make sure config uses process.env
// The config/config.json already uses process.env.DB_... variables, which is good.
// Sequelize constructor can take these directly if config object isn't used.

let sequelize;

if (process.env.DATABASE_URL && env === 'production') {
    // For production environments like Heroku that use DATABASE_URL
    sequelize = new Sequelize(process.env.DATABASE_URL, {
        dialect: 'postgres',
        protocol: 'postgres',
        dialectOptions: {
            ssl: {
                require: true,
                rejectUnauthorized: false // Adjust as per your SSL cert provider
            }
        },
        logging: false, // Disable logging for production or set to custom logger
    });
} else {
    // For development and test, use individual environment variables
    const dbName = process.env.DB_NAME || `bitedge_forum_${env}`;
    const dbUser = process.env.DB_USERNAME || 'postgres'; // Default user
    const dbPassword = process.env.DB_PASSWORD || null;
    const dbHost = process.env.DB_HOST || 'localhost';
    const dbPort = process.env.DB_PORT || 5432;

    sequelize = new Sequelize(dbName, dbUser, dbPassword, {
        host: dbHost,
        port: dbPort,
        dialect: 'postgres',
        logging: console.log, // Log SQL queries to console in dev/test
        // dialectOptions for dev if needed (e.g. local SSL)
        // dialectOptions: env === 'development' ? { ssl: { require: true, rejectUnauthorized: false } } : {}
    });
}

const models = {};
const modelsDir = path.join(__dirname, '../../models'); // Path to models directory

// Import all model files from the models directory
// This replicates what models/index.js (generated by sequelize-cli) does.
// If models/index.js is already set up correctly by sequelize-cli, we can just require that.
// Let's check if models/index.js exists and is functional first.

const modelsIndexFile = path.join(modelsDir, 'index.js');

if (fs.existsSync(modelsIndexFile)) {
    // If models/index.js exists, it usually handles model loading and associations.
    // It should export an object like { sequelize, Sequelize, User, Post, ... }
    // However, the standard models/index.js expects to be the one creating the sequelize instance
    // based on config/config.json.
    // To avoid conflict, we will use our sequelize instance and manually load models if needed,
    // or adapt models/index.js.

    // For now, let's manually load models and let models/index.js handle associations later if needed.
    fs.readdirSync(modelsDir)
        .filter(file => {
            return (file.indexOf('.') !== 0) && (file !== 'index.js') && (file.slice(-3) === '.js');
        })
        .forEach(file => {
            const model = require(path.join(modelsDir, file))(sequelize, Sequelize.DataTypes);
            models[model.name] = model;
        });

    Object.keys(models).forEach(modelName => {
        if (models[modelName].associate) {
            models[modelName].associate(models);
        }
    });

    console.log("Models loaded and associated manually.");

} else {
    console.error("Error: backend/models/index.js not found. Models cannot be loaded automatically by this script.");
    // Fallback or error if models/index.js is critical and missing
}

module.exports = sequelize; // Export the instance for db connection
// Also, it might be useful to export models from here too, or ensure models/index.js does that
// and is the single source of truth for models.
// For now, app.js will use this sequelize instance. Routes will require models directly or via models/index.js.
// Let's refine this: the standard `models/index.js` is better.
// I should modify `models/index.js` to use these env vars or ensure it's compatible.

// Revisiting: The models/index.js created by `sequelize-cli init` is the standard way.
// It reads config/config.json. My config.json now uses "ENV" to point to process.env variables.
// So, the original models/index.js should work.
// This sequelize.js file might be redundant if models/index.js is the source of truth for the instance.
// Let's assume models/index.js is the primary way to get the db object.
// This file (src/db/sequelize.js) will then just re-export from models/index.js.
// This avoids having two places where Sequelize instances are created.

// --- SIMPLIFIED APPROACH ---
// The models/index.js (created by sequelize-cli) is the source of truth for the db object
// which includes the sequelize instance and all loaded models.
// We just need to ensure it's configured correctly.
// The config/config.json is set up to use environment variables.

// This file (src/db/sequelize.js) will just re-export the db object from models/index.js
// const db = require('../../models'); // This should point to models/index.js
// module.exports = db.sequelize; // Export just the instance for authenticate()
// And other parts of the app can import db directly for models: const { User } = require('../../models');

// Let's make this file simpler and rely on the standard models/index.js
// The purpose of this file in app.js was to get the sequelize instance for .authenticate()
// So, it should just export that.
const db = require('../../models'); // This requires models/index.js
module.exports = db.sequelize; // Export the instance
// The app can then do: const { User, Post } = require('./models'); to get models.
// (Adjusting path in routes/controllers)
