const { Category, Forum } = require('../../models'); // Assuming models/index.js exports these

// List all Categories
exports.listCategories = async (req, res, next) => {
    try {
        const categories = await Category.findAll({
            // Optionally include forums count or some forums, but keep it light for a list view
            // include: [{ model: Forum, as: 'forums', attributes: ['id', 'name', 'slug'] }]
            order: [['name', 'ASC']] // Or some other preferred order
        });
        res.json(categories);
    } catch (error) {
        next(error);
    }
};

// Get a specific Category by slug (or ID) including its Forums
exports.getCategoryBySlug = async (req, res, next) => {
    try {
        const { categorySlug } = req.params;
        const category = await Category.findOne({
            where: { slug: categorySlug },
            include: [{
                model: Forum,
                as: 'forums',
                attributes: ['id', 'name', 'slug', 'description', 'topic_count', 'post_count'], // Add fields as needed
                order: [['display_order', 'ASC'], ['name', 'ASC']]
            }]
        });

        if (!category) {
            return res.status(404).json({ message: 'Category not found.' });
        }
        res.json(category);
    } catch (error) {
        next(error);
    }
};

// Create a new Category (Admin only - basic stub, auth middleware needed later)
exports.createCategory = async (req, res, next) => {
    // TODO: Add authentication and authorization (admin only)
    try {
        const { name, description, slug } = req.body;
        if (!name) {
            return res.status(400).json({ message: 'Category name is required.' });
        }

        // Slug can be auto-generated by model hook if not provided
        const newCategory = await Category.create({ name, description, slug });
        res.status(201).json(newCategory);
    } catch (error) {
        if (error.name === 'SequelizeUniqueConstraintError') {
            return res.status(409).json({ message: 'Category name or slug already exists.', errors: error.errors });
        }
        next(error);
    }
};

// TODO: Update Category (Admin only)
// TODO: Delete Category (Admin only)
