const { Forum, Topic, User, Post, Category } = require('../../models');

// Get a specific Forum by slug, including its Topics
exports.getForumBySlug = async (req, res, next) => {
    try {
        const { forumSlug } = req.params; // Assuming global forum slugs for now
                                          // If slugs are per-category, need categorySlug too.
                                          // For simplicity, plan assumed /api/forums/:forumSlug/topics/

        const forum = await Forum.findOne({
            where: { slug: forumSlug },
            include: [
                {
                    model: Category,
                    as: 'category',
                    attributes: ['id', 'name', 'slug']
                },
                {
                    model: Topic,
                    as: 'topics',
                    attributes: ['id', 'title', 'slug', 'createdAt', 'reply_count', 'view_count', 'last_activity_at'],
                    include: [
                        { model: User, as: 'user', attributes: ['id', 'username'] }, // Topic author
                        // Optionally include last post info for each topic
                        {
                            model: Post,
                            as: 'lastPost', // This alias must match Topic model association
                            attributes: ['id', 'createdAt'],
                            include: [{ model: User, as: 'user', attributes: ['id', 'username'] }]
                        }
                    ],
                    order: [['last_activity_at', 'DESC']], // Show most recent topics first
                    limit: 25, // Paginate topics later
                    offset: 0  // Paginate topics later
                }
            ]
        });

        if (!forum) {
            return res.status(404).json({ message: 'Forum not found.' });
        }
        res.json(forum);
    } catch (error) {
        next(error);
    }
};

// Create a new Forum (Admin only - basic stub)
exports.createForum = async (req, res, next) => {
    // TODO: Add authentication and authorization (admin only)
    try {
        const { name, description, slug, categoryId, display_order } = req.body; // categoryId is crucial
        if (!name || !categoryId) {
            return res.status(400).json({ message: 'Forum name and categoryId are required.' });
        }

        const category = await Category.findByPk(categoryId);
        if (!category) {
            return res.status(404).json({ message: 'Category not found for the given categoryId.' });
        }

        // Slug can be auto-generated by model hook if not provided and if unique globally
        // If slug is unique per category, model hook needs adjustment or manual creation here.
        const newForum = await Forum.create({
            name,
            description,
            slug, // if provided, else model hook
            categoryId,
            display_order
        });
        res.status(201).json(newForum);
    } catch (error) {
        if (error.name === 'SequelizeUniqueConstraintError') {
            // This will trigger if (categoryId, slug) is not unique, or if global slug is not unique
            return res.status(409).json({ message: 'Forum slug already exists within this category or globally.', errors: error.errors });
        }
        next(error);
    }
};


// List topics within a specific forum (already covered by getForumBySlug, but can be a dedicated endpoint)
// GET /api/forums/:forumSlug/topics - This is handled by getForumBySlug's include.
// If separate pagination/filtering for topics is needed, a dedicated controller/route is better.

// TODO: Update Forum (Admin only)
// TODO: Delete Forum (Admin only)
