const { Topic, Post, User, Forum } = require('../../models');
const sequelize = require('../db/sequelize'); // For transactions if needed

// Get a specific Topic by slug, including its Posts
exports.getTopicBySlug = async (req, res, next) => {
    try {
        const { topicSlug } = req.params;

        const topic = await Topic.findOne({
            where: { slug: topicSlug },
            include: [
                { model: User, as: 'user', attributes: ['id', 'username', 'avatar_url'] }, // Topic author
                {
                    model: Forum,
                    as: 'forum',
                    attributes: ['id', 'name', 'slug'],
                    include: [{model: Category, as: 'category', attributes: ['id', 'name', 'slug']}]
                },
                {
                    model: Post,
                    as: 'posts',
                    attributes: ['id', 'content', 'createdAt', 'updatedAt', 'parentPostId'],
                    include: [
                        { model: User, as: 'user', attributes: ['id', 'username', 'avatar_url'] } // Post author
                    ],
                    order: [['createdAt', 'ASC']], // Show posts in chronological order
                    // Add pagination for posts later
                    // limit: 10,
                    // offset: 0
                }
            ]
        });

        if (!topic) {
            return res.status(404).json({ message: 'Topic not found.' });
        }

        // Increment view count (simple version, could be more robust to avoid duplicates)
        // Consider doing this async or with a separate tracking service for high traffic
        topic.view_count = (topic.view_count || 0) + 1;
        await topic.save();

        res.json(topic);
    } catch (error) {
        next(error);
    }
};

// Create a new Topic within a Forum
// This controller method would be called from a route like /api/forums/:forumSlug/topics
exports.createTopicInForum = async (req, res, next) => {
    const t = await sequelize.transaction(); // Start a transaction

    try {
        const { forumSlug } = req.params; // from the route
        const { title, content } = req.body; // Content for the first post
        const userId = req.user?.userId; // Assuming authenticateToken middleware adds req.user

        if (!userId) {
            await t.rollback();
            return res.status(401).json({ message: 'Authentication required to create a topic.' });
        }
        if (!title || !content) {
            await t.rollback();
            return res.status(400).json({ message: 'Topic title and initial post content are required.' });
        }

        const forum = await Forum.findOne({ where: { slug: forumSlug }, transaction: t });
        if (!forum) {
            await t.rollback();
            return res.status(404).json({ message: 'Forum not found.' });
        }

        // Create the topic
        // Slug will be auto-generated by Topic model hook
        const newTopic = await Topic.create({
            title,
            forumId: forum.id,
            userId: userId,
            // last_activity_at will default to now
        }, { transaction: t });

        // Create the initial post for the topic
        const firstPost = await Post.create({
            content,
            topicId: newTopic.id,
            userId: userId
        }, { transaction: t });

        // Update topic with lastPostId and last_activity_at
        newTopic.lastPostId = firstPost.id;
        newTopic.last_activity_at = firstPost.createdAt; // Or newTopic.createdAt
        // reply_count is 0 for a new topic, initial post is not a "reply" to itself
        await newTopic.save({ transaction: t });

        // Update forum's topic_count and post_count, and lastTopicId
        forum.topic_count = (forum.topic_count || 0) + 1;
        forum.post_count = (forum.post_count || 0) + 1; // For the first post
        forum.lastTopicId = newTopic.id; // Update last topic in forum
        await forum.save({ transaction: t });

        await t.commit();

        // Fetch the created topic with some associations for the response
        const resultTopic = await Topic.findByPk(newTopic.id, {
            include: [
                { model: User, as: 'user', attributes: ['id', 'username'] },
                { model: Forum, as: 'forum', attributes: ['id', 'name', 'slug'] }
            ]
        });

        res.status(201).json(resultTopic);

    } catch (error) {
        await t.rollback();
        if (error.name === 'SequelizeUniqueConstraintError' && error.fields && error.fields.slug) {
             return res.status(409).json({ message: 'Topic slug generation conflict. Please try a slightly different title or try again.' });
        }
        next(error);
    }
};

// TODO: Update Topic (Admin/Owner)
// TODO: Delete Topic (Admin/Owner)
// TODO: Lock/Unlock Topic (Admin/Moderator)
// TODO: Pin/Unpin Topic (Admin/Moderator)
