const { Topic, Post, User, Forum } = require('../../models');
const sequelize = require('../db/sequelize'); // For transactions if needed

// Get a specific Topic by slug, including its Posts
exports.getTopicBySlug = async (req, res, next) => {
    try {
        const { topicSlug } = req.params;

        const topic = await Topic.findOne({
            where: { slug: topicSlug },
            include: [
                { model: User, as: 'user', attributes: ['id', 'username', 'avatar_url'] }, // Topic author
                {
                    model: Forum,
                    as: 'forum',
                    attributes: ['id', 'name', 'slug'],
                    include: [{model: Category, as: 'category', attributes: ['id', 'name', 'slug']}]
                },
                {
                    model: Post,
                    as: 'posts',
                    attributes: ['id', 'content', 'createdAt', 'updatedAt', 'parentPostId'],
                    include: [
                        { model: User, as: 'user', attributes: ['id', 'username', 'avatar_url'] } // Post author
                    ],
                    order: [['createdAt', 'ASC']], // Show posts in chronological order
                    // Add pagination for posts later
                    // limit: 10,
                    // offset: 0
                }
            ]
        });

        if (!topic) {
            return res.status(404).json({ message: 'Topic not found.' });
        }

        // Increment view count (simple version, could be more robust to avoid duplicates)
        // Consider doing this async or with a separate tracking service for high traffic
        topic.view_count = (topic.view_count || 0) + 1;
        await topic.save();

        res.json(topic);
    } catch (error) {
        next(error);
    }
};

// Create a new Topic within a Forum
// This controller method would be called from a route like /api/forums/:forumSlug/topics
exports.createTopicInForum = async (req, res, next) => {
    const t = await sequelize.transaction(); // Start a transaction

    try {
        const { forumSlug } = req.params; // from the route
        const { title, content } = req.body; // Content for the first post
        const userId = req.user?.userId; // Assuming authenticateToken middleware adds req.user

        if (!userId) {
            await t.rollback();
            return res.status(401).json({ message: 'Authentication required to create a topic.' });
        }
        if (!title || !content) {
            await t.rollback();
            return res.status(400).json({ message: 'Topic title and initial post content are required.' });
        }

        const forum = await Forum.findOne({ where: { slug: forumSlug }, transaction: t });
        if (!forum) {
            await t.rollback();
            return res.status(404).json({ message: 'Forum not found.' });
        }

        // Create the topic
        // Slug will be auto-generated by Topic model hook
        const newTopic = await Topic.create({
            title,
            forumId: forum.id,
            userId: userId,
            // last_activity_at will default to now
        }, { transaction: t });

        // Create the initial post for the topic
        const firstPost = await Post.create({
            content,
            topicId: newTopic.id,
            userId: userId
        }, { transaction: t });

        // Update topic with lastPostId and last_activity_at
        newTopic.lastPostId = firstPost.id;
        newTopic.last_activity_at = firstPost.createdAt; // Or newTopic.createdAt
        // reply_count is 0 for a new topic, initial post is not a "reply" to itself
        await newTopic.save({ transaction: t });

        // Update forum's topic_count and post_count, and lastTopicId
        forum.topic_count = (forum.topic_count || 0) + 1;
        forum.post_count = (forum.post_count || 0) + 1; // For the first post
        forum.lastTopicId = newTopic.id; // Update last topic in forum
        await forum.save({ transaction: t });

        await t.commit();

        // Fetch the created topic with some associations for the response
        const resultTopic = await Topic.findByPk(newTopic.id, {
            include: [
                { model: User, as: 'user', attributes: ['id', 'username'] },
                { model: Forum, as: 'forum', attributes: ['id', 'name', 'slug'] }
            ]
        });

        res.status(201).json(resultTopic);

    } catch (error) {
        await t.rollback();
        if (error.name === 'SequelizeUniqueConstraintError' && error.fields && error.fields.slug) {
             return res.status(409).json({ message: 'Topic slug generation conflict. Please try a slightly different title or try again.' });
        }
        next(error);
    }
};

// Update a Topic's title
exports.updateTopic = async (req, res, next) => {
    try {
        const { topicSlug } = req.params;
        const { title } = req.body;
        const { userId, isAdmin } = req.user;

        if (!title) {
            return res.status(400).json({ message: 'Title cannot be empty.' });
        }

        const topic = await Topic.findOne({ where: { slug: topicSlug } });

        if (!topic) {
            return res.status(404).json({ message: 'Topic not found.' });
        }

        if (topic.userId !== userId && !isAdmin) {
            return res.status(403).json({ message: 'Forbidden: You do not have permission to edit this topic.' });
        }

        topic.title = title;
        // Note: If slug is based on title, it should be regenerated here as well,
        // which could be complex if slugs must be unique forever.
        // For simplicity, we are not changing the slug.
        await topic.save();

        res.json(topic);

    } catch (error) {
        next(error);
    }
};

// Delete a Topic
exports.deleteTopic = async (req, res, next) => {
    const t = await sequelize.transaction();
    try {
        const { topicSlug } = req.params;
        const { userId, isAdmin } = req.user;

        const topic = await Topic.findOne({ where: { slug: topicSlug }, transaction: t });

        if (!topic) {
            await t.rollback();
            return res.status(404).json({ message: 'Topic not found.' });
        }

        if (topic.userId !== userId && !isAdmin) {
            await t.rollback();
            return res.status(403).json({ message: 'Forbidden: You do not have permission to delete this topic.' });
        }

        const forum = await Forum.findByPk(topic.forumId, { transaction: t });

        // The number of posts to decrement is the topic's reply_count + the initial post (1)
        const postsInTopicCount = (topic.reply_count || 0) + 1;

        // Deleting the topic will cascade and delete all its posts due to model association settings.
        await topic.destroy({ transaction: t });

        if (forum) {
            forum.topic_count = Math.max(0, (forum.topic_count || 1) - 1);
            forum.post_count = Math.max(0, forum.post_count - postsInTopicCount);
            // TODO: Add logic here to find the new lastTopicId for the forum.
            // This would involve finding the most recently active topic remaining in the forum.
            await forum.save({ transaction: t });
        }

        await t.commit();
        res.status(204).send();

    } catch (error) {
        await t.rollback();
        next(error);
    }
};

// TODO: Lock/Unlock Topic (Admin/Moderator)
// TODO: Pin/Unpin Topic (Admin/Moderator)
